### ISSUE TITLE
Uncaught (in promise) TypeError

### ISSUE THREAD

**Issue by Mausoomi12** [kunaltyagi9/MERN-Stack-Projects#17]
Cannot read properties of undefined (reading 'path')
    at App.js:19:28
    at d (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at o (asyncToGenerator.js:3:20)
    at i (asyncToGenerator.js:22:9)

**Comment by kunaltyagi9** [comment]
The variable using which you are calling path has a value undefined.
